{{- $labels := merge
  (fromYaml (include "commonLabels" $))
  .Values.global.labels
-}}
{{- $annotations :=
  .Values.global.annotations
-}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with $labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ quote $v }}
    {{- end }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ quote $v }}
    {{- end }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "name" . }}
  {{- with $labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ quote $v }}
    {{- end }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ quote $v }}
    {{- end }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "name" . }}
  {{- with $labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ quote $v }}
    {{- end }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ quote $v }}
    {{- end }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "name" . }}
  apiGroup: rbac.authorization.k8s.io
