apiVersion: v1
entries:
  csi-driver-rclone:
  - apiVersion: v2
    appVersion: v1.0.0
    created: "2024-03-05T12:03:59.083640955-06:00"
    description: rclone csi driver, packaged for k8s
    digest: 8a46317890fa8ae89ec5cf671101c41b926b0ac7c19531d84cb537dcef016998
    icon: https://upload.wikimedia.org/wikipedia/commons/e/e4/Rclone_wide_logo.svg
    name: csi-driver-rclone
    sources:
    - https://github.com/cornfeedhobo/csi-driver-rclone
    type: application
    urls:
    - csi-driver-rclone-v1.0.0.tgz
    version: v1.0.0
generated: "2024-03-05T12:03:59.082634859-06:00"
