name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Set job context
        id: context
        run: >
          echo "tags=
          --tag=docker.io/${{ github.repository }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          --tag=ghcr.io/${{ github.repository }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          " >> $GITHUB_OUTPUT
          echo "push=
          docker.io/${{ github.repository }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          ghcr.io/${{ github.repository }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          " >> $GITHUB_OUTPUT

      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Go, using the version from go.mod
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run test and build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          go version
          make container \
            "GO_ARCH=amd64 arm arm64" \
            "GO_OS=linux" \
            "TAGS=$(awk '{$1=$1};1' <<<'${{ steps.context.outputs.tags }}')"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: bin/csi-driver-rclone*

      - name: Upload docker images
        run: |
          docker push ${{ steps.context.outputs.push }}
